{% set version = "0.4" %}
{% set sha256 = "47b5cb48f8e036497cd73b96de305cecb4070e9ecbc908724afcbd2224edccde" %}
{% set pkg_name = "port-for" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: port_for-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - port_for
  commands:
    - port-for --version

about:
  home: https://github.com/kmike/port-for/
  license: MIT
  summary: 'port-for is a command-line utility and a python library that helps with local TCP ports managment'
  description: |
    port-for is a command-line utility and a python library that helps with local TCP ports managment.
    port-for <foo> script finds an unused port and associates it with <foo>. Subsequent calls will
    return the same port number.
  dev_url: https://github.com/kmike/port-for

extra:
  recipe-maintainers:
    - chohner
