travis:
  secure:
    BINSTAR_TOKEN: W2T9dByBWcEcl120ttHnO75XbETDPyfb9FSrQVnlG+yAChEeN1EP2gk/z3W61b+Pi120Pu7A0npDZmad6CWFvhBDI4qUGhqYTQ05Pf7/5zJ64gB013Hdl3IyVLODV+9K12kdVz0G7MkEBpQNL+EzuzqOdHuwx/U3K+j+qOxtHhRSw8kyFAiIwJrrZtUiOX3E3QOJDacqUcZWIzqQmzMuRzItlVpoLBCyRbBDZ7ukfBGw1ErYfKxiHzN/sOVRZJN0HP0upcOcZPqUUqP0j3kNYaB6hzAI6DYaeWC2LTQ7TW+r14LW0KNfHpDXbJsgJubd0nj0SJ85Rmt8b1qQG49r+siTPIVoZ4KhmWJg9lo9WMeFL+LaSL10JpNeSnTEyWcb7xrfy4MrTO9Ac2n0tsqGVgNtwWCfJZY/vWwUf8r7XNGy0hE/v7T9zfOo5sXmpsYLKIAGkUCNC90o+rA9PfaK/0hNQF0WZ2HUZLtsxzuoAWNYRW4w2dHlJ5a8xhhDrSe7JOiYQNTg7XrJYsZFspsCPwK5bl9KufyhrNDMRn6dfi2psHYmgzgBjlBIipmxlYQ0+I8hF+igbyZoAYL6ih2ZfUVRZjk37vYJvPqAu3AK7quGr96DYnXhGKT+U7NPpZ82N5QCpmf5Vs67GUUHFVwj4VTu8BMXFrRO8DYZJ+EZ7gE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
