travis:
  secure:
    BINSTAR_TOKEN: CW0FPbcJK3GK3mnVIEDqEn5QpnEcoEtpuSXSyQbhynIItMODSyncvIxNLUXOrDM7RKebRwON5uRnKM57WSjqgU89SmiV4KaoBdl5y2OIu8cBNckBX5/gxOPNW+SacyK49CIN5kbRwT9+7si0oEQhVbRO3B76WQHVDmX3EM2Ue7r5tHy5OA9Wczt5ApX7C1Kf5XE447ITB0EQ95dpzpvcHZ28i4tXD0U+rjJ/xNkKjLWyGYT6ZTJMHY0LGwL5WeaKEv1+pbBqXmIrRWg0HNZS1wv72GgxL2Gh2P/dwt3nthEtGKMnYIQP3ylu4AzplKDhLjjljLYvurxhhaVYJTs1s599j5m4impHY2V3nGR7flopGVYYz+uvSAnPyetiQwOJ7Jc/gEGy1jn/rL2FJAscGDhKJHncyI7uF1Z56UCynl3S5zC9ZcD/ek2IME5ymGbhT5xrMBXPuUJbWcu5URu3gGCxDi4BlCT9RX74YGRLcCdLyuPt+FJ5nUepvDYgH+IAMVjv0NQZdn8ywE5E4WNkNPUHxN69SveVfCfLXr1GNcbgdRsWP76fF/EX/w9ffFIlufeDRpj9DjCPDEUE+xin2jWsF0wUqAPj+vgRenc7QwQyDbatgpYStkqkw7UCm+FxglPPZfHm8B3DgdolHKdej+39LypxG8XX+XzOy3oEVf8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
